skip pre-release checks

diff --git a/.github/workflows/cloud-security-automated-release.yml b/.github/workflows/cloud-security-automated-release.yml
--- a/.github/workflows/cloud-security-automated-release.yml
+++ b/.github/workflows/cloud-security-automated-release.yml
@@ -72,37 +72,37 @@ on:
         value: ${{ jobs.release-in-jira.outputs.new-version }}
 
 jobs:
-  pre-release-checks:
-    name: Pre-release checks
-    runs-on: ubuntu-latest
-    permissions:
-      statuses: read
-      contents: write
-      pull-requests: write
-      id-token: write
-    steps:
-      - name: Check Releasability Status
-        uses: SonarSource/release-github-actions/check-releasability-status@5f9e625213d4288f53555490fb4919295db40de2
-        with:
-          branch: ${{ inputs.branch }}
-          with-optional-checks: false
-
-      - name: Update Rule Metadata
-        id: update-rule-metadata
-        uses: SonarSource/release-github-actions/update-rule-metadata@5f9e625213d4288f53555490fb4919295db40de2
-
-      - name: Check Rule Metadata Changes
-        if: steps.update-rule-metadata.outputs.has-changes == 'true'
-        run: |
-          echo "::error::Rule metadata changes detected. The generated PR needs to be merged first before continuing with the release."
-          echo "::error::Pull Request URL: ${{ steps.update-rule-metadata.outputs.pull-request-url }}"
-          echo "::error::Please merge the PR and restart this workflow."
-          exit 1
+#  pre-release-checks:
+#    name: Pre-release checks
+#    runs-on: ubuntu-latest
+#    permissions:
+#      statuses: read
+#      contents: write
+#      pull-requests: write
+#      id-token: write
+#    steps:
+#      - name: Check Releasability Status
+#        uses: SonarSource/release-github-actions/check-releasability-status@5f9e625213d4288f53555490fb4919295db40de2
+#        with:
+#          branch: ${{ inputs.branch }}
+#          with-optional-checks: false
+#
+#      - name: Update Rule Metadata
+#        id: update-rule-metadata
+#        uses: SonarSource/release-github-actions/update-rule-metadata@5f9e625213d4288f53555490fb4919295db40de2
+#
+#      - name: Check Rule Metadata Changes
+#        if: steps.update-rule-metadata.outputs.has-changes == 'true'
+#        run: |
+#          echo "::error::Rule metadata changes detected. The generated PR needs to be merged first before continuing with the release."
+#          echo "::error::Pull Request URL: ${{ steps.update-rule-metadata.outputs.pull-request-url }}"
+#          echo "::error::Please merge the PR and restart this workflow."
+#          exit 1
 
   prepare-release:
     name: Prepare release
     runs-on: ubuntu-latest
-    needs: pre-release-checks
+#    needs: pre-release-checks
     permissions:
       statuses: read
       contents: read
